### ISSUE TITLE
benchmarking-queries.sql is missing but not mentioned in readme

### ISSUE THREAD

**Issue by philippneugebauer** [qaware/mysql-benchmark-tool#1]
First of all, your tool seems to be really useful, but when I tried to run it I got the following error:

```
[main] ERROR de.qaware.mysqlbenchmark.Main - File not found.
java.io.FileNotFoundException: benchmarking-queries.sql (Das System kann die ang
egebene Datei nicht finden)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at de.qaware.mysqlbenchmark.logfile.QueryParser.parseLogFile(QueryParser
.java:82)
        at de.qaware.mysqlbenchmark.Main.main(Main.java:75)
```

Unfortunately, there is nothing documented about this file.

**Comment by qa-felix-kelm** [comment]
Thanks for your comment. It seems that you did not provide a valid logfile with the -log parameter. If you don't provide the parameter, 'benchmarking-queries.sql' is taken as default. If you start the jar without parameters, you get some infos about possible parameters. 

I adjusted the error message in case of missing logfiles for better understanding. Thanks for your feedback.
